version: 1
default: "&2[公民]"
TAB: false
SXname:
  Attackadd: "§1攻击加成"
  Attack: "§2基础攻击"
  CritDamage: "§3暴击伤害"
  CritChance: "§4暴击几率"
  Life: "§5吸血几率"
  Lifedraw: "§6吸血倍率"
  Armordamage: "§7破甲伤害"
  Armorchance: "§8破甲几率"
  Realdamage: "§9真实伤害"
  PVPdamage: "§0PVP伤害"
  Fatal: "§a致命一击"
  Wither: "§b凋零几率"
  Poison: "§c中毒几率"
  Frozen: "§d冰封几率"
  Weakening: "§e弱化几率"
  nausea: "§f混乱几率"
  Blindness: "§1致盲几率"
  Armoradd: "§a防御加成"
  Armor: "§2防御"
  Dogde: "§b闪避"
  ThornsChance: "§3反伤几率"
  ThornsValue: "§c反伤倍率"
Message:
  give: "添加称号成功"
  xf: "称号续费成功"
  remove: "成功删除称号"
  permanent: "§2+§d永不过期§2+"
  expirationtime: "§2=§2过期时间"
  use: "§d使用中"
  unuse: "§a未使用"